doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: false

    #connection: default

    #em: default

        #storage:
        # Default (SQL table) metadata storage configuration
        #table_storage:
        #table_name: 'doctrine_migration_versions'
        #version_column_name: 'version'
        #version_column_length: 192
    #executed_at_column_name: 'executed_at'

    # Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    #organize_migrations: false

    # Path to your custom migrations template
    #custom_template: ~

    # Run all migrations in a transaction.
    #all_or_nothing: false

    # Adds an extra check in the generated migrations to ensure that is executed on the same database type.
    #check_database_platform: true

    # Whether or not to wrap migrations in a single transaction.
    #transactional: true

    # Whether or not to enable the profiler collector to calculate and visualize migration status. This adds some queries overhead.
    # enable_profiler: false

        #services:
        # Custom migration sorting service id
        #'Doctrine\Migrations\Version\Comparator': ~

        # Custom migration classes factory
    #'Doctrine\Migrations\Version\MigrationFactory': ~

        #factories:
        # Custom migration sorting service id via callables (MyCallableFactory must be a callable)
    #'Doctrine\Migrations\Version\Comparator': 'MyCallableFactory'
